apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trident
  namespace: default
  labels:
    app: trident.netapp.io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
