apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: bronze
provisioner: netapp.io/trident
parameters:
  media: "hdd"
  provisioningType: "thin"
  snapshots: "true"
  requiredStorage: "solidfire_10.0.0.1:Bronze"

