apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  tridentImage: docker.io/netapp/trident:22.01.0
  imagePullSecrets:
  - thisisasecret
