apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-operator
  namespace: {{ .Release.Namespace }}
  {{- if and (ne .Values.cloudIdentity "") (ne .Values.cloudProvider "") }}
  {{- $cloudIdentity := trimPrefix "'" .Values.cloudIdentity }}
  {{- $cloudIdentity = trimSuffix "'" $cloudIdentity }}
  {{- $cloudIdentityPair := regexSplit ": " $cloudIdentity 2 }}
  annotations:
    {{ first $cloudIdentityPair }}: {{ last $cloudIdentityPair }}
  {{- end }}
  labels:
    app: operator.trident.netapp.io
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
- name: {{ . }}
{{- end }}
{{- end }}
